### ISSUE TITLE
Cannot compile/build

### ISSUE THREAD

**Issue by halvorlu** [orgzly/org-java#9]
I'm having trouble compiling/building `org-java`. Building from Android Studio or from the command-line with `gradle build` yields the same error: 

```
Could not evaluate onlyIf predicate for task ':signArchives'.
path may not be null or empty string. path=''
```

I might (probably) have set up something incorrectly or misunderstood how to build it correctly. Would be grateful for advice on how to compile and deploy to an Android device.

**Comment by nevenz** [comment]
You should be using a wrapper, does `./gradlew build` work?

**Comment by halvorlu** [comment]
`./gradlew build` gives the same result.

**Comment by nevenz** [comment]
Looks like it happens when I remove

```
signing.keyId=...
signing.password=...
signing.secretKeyRingFile=...
```

from `~/.gradle/gradle.properties`.

I'm not sure if it's normal to do the signing for `build` task. It doesn't sound like it, I'll have to check that.

You can try some other task for now, perhaps `./gradlew jar`.
